name: PySpark Data Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Install Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # OpenJDK
        java-version: '11'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/

    - name: Run main script
      run: python src/main.py
